// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZONdiQt4Kfy4XT7vg-jNd4gY56zuS9bY',
    appId: '1:351948581676:android:d2d966b36365ef94e89a89',
    messagingSenderId: '351948581676',
    projectId: 'presence-4b647',
    storageBucket: 'presence-4b647.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUCaUAK-VTqzXwWaVUtcFIaerqhMXwPLk',
    appId: '1:351948581676:ios:818aadc07082e83de89a89',
    messagingSenderId: '351948581676',
    projectId: 'presence-4b647',
    storageBucket: 'presence-4b647.appspot.com',
    iosClientId: '351948581676-qv32jm95gen90gffidj00ee4rgufatm5.apps.googleusercontent.com',
    iosBundleId: 'com.rianjaidi.presence',
  );
}
